Feature/init db
UpstageAI/slack-event-subscriptions pull request #10
Opened 2021-01-13 09:03 UTC by thejungwon

일단 pytest를 진행하기 전에, 말씀하신 table 생성과 삭제를 위해 table 관련된 함수를 새로 작성하였습니다.

그리고, table의 생성과 삭제는 외부에서 호출하는 식으로 처리하도록 변경하였습니다

```
zappa invoke dev 'from db import create_table;create_table()' --raw
zappa invoke dev 'from db import delete_table;delete_table()' --raw
```

2021-01-13 22:30 UTC, hunkim requested changes

2021-01-13 22:30 UTC, hunkim commented on db.py
> +    event_table_name = event_table_name if event_table_name else EVENT_TABLE
event_table_name = event_table_name if event_table_name else EVENT_TABLE
대신 위 함수에서

create_table(dynamodb=None, event_table_name=EVENT_TABLE...) 로 하시면 됩니다.

2021-01-13 22:30 UTC, hunkim commented on db.py
> +            TableName=EVENT_TABLE,
DB schema는 외부 별도 파일로 뺄까요? db_schema.json?

2021-01-13 22:30 UTC, hunkim commented on db.py
>  def get_event_key(event):
커멘트가 안달아져서 여기다 추가 합니다. .DS_Store는 파일 삭제해도 될듯합니다.

2021-01-14 02:49 UTC, thejungwon commented
unittest 브랜치에 포함된 내용이므로 Close

2021-01-14 02:49 UTC, closed without merging